name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
        source-url: https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json
      env:
        NUGET_AUTH_TOKEN:  ${{secrets.NUGET_API_KEY}}
        # NUGET_AUTH_TOKEN: '%NUGET_AUTH_TOKEN%'
    - name: Restore dependencies
      run: dotnet restore
      env:
        NUGET_AUTH_TOKEN:  ${{secrets.NUGET_API_KEY}}
    - name: Build
      run: dotnet build --no-restore -c Release
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Publish
      uses: brandedoutcast/publish-nuget@v2.5.2
      with:
        PROJECT_FILE_PATH: ListClassToExcel/ExcelService.csproj
        NUGET_KEY: ${{secrets.NUGET_API_KEY}}
