name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: ['3.1.x', '5.0.x', '6.0.x']

    steps:
    - uses: actions/labeler@v2
      with: 
        repo-token: ${{ secrets.GITHUB_TOKEN }}
    - uses: actions/checkout@v2
    - name: Setup .NET Core 3.1
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
        # dotnet-version: ['3.0', '3.1.x', '5.0.x', '6.0.x']
        source-url: https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json
      env:
        NUGET_AUTH_TOKEN:  ${{secrets.NUGET_API_KEY}}
        # NUGET_AUTH_TOKEN: '%NUGET_AUTH_TOKEN%'
    - name: Setup .NET Core 5.0
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
        source-url: https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json
      env:
        NUGET_AUTH_TOKEN:  ${{secrets.NUGET_API_KEY}}
    - name: Setup .NET Core 6.0
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
        source-url: https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json
      env:
        NUGET_AUTH_TOKEN:  ${{secrets.NUGET_API_KEY}}

    - name: Restore dependencies
      run: dotnet restore
      env:
        GITHUB_TOKEN:  ${{secrets.NUGET_API_KEY}}
    - name: Build
      run: dotnet build --no-restore -c Release
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Publish
      run: dotnet nuget push ./bin/Release/*.nupkg --skip-duplicate # --no-symbols true --source "github"
      # uses: brandedoutcast/publish-nuget@v2.5.2
      # with:
        # PROJECT_FILE_PATH: ListClassToExcel/ExcelService.csproj
        # NUGET_KEY: ${{secrets.NUGET_API_KEY}}
